import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { primaryFont } from "@/theme";



export const metadata: Metadata = {
  title: "Readings App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={primaryFont.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
